### ISSUE TITLE
installing `gcc5gfortran`

### ISSUE THREAD

**Issue by nhejazi** [r-hub/solarischeck#10]
thanks for the work putting this together, it's been very helpful for debugging issues arising on CRAN's Solaris builds. i've been trying to debug an `Rcpp`-based package and just wanted to note here that manually installing [`gcc5gfortran`](https://www.opencsw.org/packages/gcc5gfortran/), via `sudo pkgutil -y -i gcc5gfortran`, turned out to be necessary to install `RcppEigen`. i have next to no experience working with Solaris, and this isn't strictly an issue with this repo, but i wanted to note it here in case it saves anyone else the couple hours it took me to figure out the string of errors that led me to this.

**Comment by gaborcsardi** [comment]
Hi, yes, this is the list of opencsw packages installed on R-hub's Solaris machine: https://github.com/r-hub/solarischeck/blob/master/sysreqs.txt#L63

We did not install all of them to keep the VM downloads at https://files.r-hub.io/solaris/ small. Plus occasionally we extend the list, and it would be cumbersome to always update the VM images. You can install all of them if you like.
