### ISSUE TITLE
'fs' package installation failing

### ISSUE THREAD

**Issue by shikokuchuo** [r-hub/solarischeck#9]
Hi, Is there a trick to installing the 'fs' package on a Solaris machine built using this repo?
I have gmake installed which is listed as a requirement.

The error:
--

    * installing source package 'fs' ...
    ** package 'fs' successfully unpacked and MD5 sums checked
    ** using staged installation
    ** libs
    make: fatal error in reader: Makevars, line 2: Unexpected end of line seen
    ERROR: compilation failing for package 'fs'

--

I have the machine to a point where I can run R CMD check, but 'fs' is the last dependency of 'devtools' that fails and it would be nice to have 'devtools'. Presumably there is a way as it works for CRAN and the R-hub Solaris builder. Thanks.

**Comment by gaborcsardi** [comment]
Did you set `export MAKE=gmake`?

**Comment by shikokuchuo** [comment]
Amazing! totally works. Thanks for creating this resource.

**Comment by shikokuchuo** [comment]
Thanks for your help earlier, and the incredible work to make this available.
I have written up my install experience to hopefully make it easier for others: https://shikokuchuo.net/posts/14-r-on-solaris/
Please feel free to use it as you wish if you want to update the repo README etc.

**Comment by gaborcsardi** [comment]
Thanks! Btw. this is probably too late now, but you can also download Solaris VMs for VirtualBox and VMWare from https://files.r-hub.io/solaris/
